### ISSUE TITLE
Checksum mismatch breaks the adapter

### ISSUE THREAD

**Issue by climategadgets** [home-climate-control/xbee-api-reactive#18]
### Expected Behavior
Adapter initializes and keeps working normally.

### Actual Behavior
(observed on rev. 6198fb7183b4dc107d9bc62ec96c1f6195092b14)
On startup with some hardware configurations, the exception trace below is printed onto `stdout`, no further communication is happening.

### Suspected Cause
Mismatch between the desired and the actual API state (byte values are escape (`0x7D`) and XON (`0x11`)), the packet is not properly unescaped, and the checksum is not calculated on correct payload.

### Contributing Factors
The exception propagates unchecked and kills the reader thread.

```
Exception in thread "XBeeReader" java.lang.IllegalArgumentException: Checksum mismatch, expected 0x7D, actual 0x11
        at com.homeclimatecontrol.xbee.response.ResponseReader.verifyChecksum(ResponseReader.java:116)
        at com.homeclimatecontrol.xbee.response.ResponseReader.read(ResponseReader.java:50)
        at com.homeclimatecontrol.xbee.HardwareReader.readFrame(HardwareReader.java:90)
        at com.homeclimatecontrol.xbee.HardwareReader.processFrame(HardwareReader.java:71)
        at com.homeclimatecontrol.xbee.HardwareReader.read(HardwareReader.java:53)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by climategadgets** [comment]
Fixed.
